Update for Flarum v1
FriendsOfFlarum/merge-discussions pull request #28
Opened 2021-06-05 20:26 UTC by datitisev

2021-06-05 21:44 UTC, imorland reviewed
`category` in `composer.json` should also be changed to `feature`

Just my opinion, but we should probably also update the uses of `app()` to `resolve`. I know `app` is still available, but as it's permamently deprecated, we should lead by example and use the `resolve` method, imo

2021-06-05 21:44 UTC, imorland commented on README.md
>  Use [Bazaar](https://discuss.flarum.org/d/5151-flagrow-bazaar-the-extension-marketplace) or install manually with composer:
We should remove the Bazaar reference

2021-06-05 21:45 UTC, imorland commented
![image](https://user-images.githubusercontent.com/16573496/120906243-a487a080-c64f-11eb-81d8-b132e4bb3457.png)

After merging a previously split discussion, the modal remains open, and this is added to the destination discussion

2021-06-06 12:13 UTC, datitisev commented
> After merging a previously split discussion, the modal remains open, and this is added to the destination discussion

This will happen regardless of if split was used or not - e.g. if the issue with modal not closing happens and you click merge multiple times.

> Using merge into me, the merge modal remains open after the merge completes, rather than returning to the discussion

Had this happen but thought it was because I had changed something in the JS - I see now that was not the issue.

2021-06-06 13:20 UTC, datitisev commented
> Merged discussions are not removed from the discussion list after successful merge, if merged from within a discussion

I could not reproduce this.

I think I have fixed the other errors I found, howevfer.

2021-06-06 19:02 UTC, Ralkage commented
Just tested and haven't experienced any of the issues mentioned even after the recent changes @datitisev made; I believe we are good to merge this.

2021-06-06 19:03 UTC, Ralkage approved these changes

2021-06-06 20:35 UTC, imorland requested changes
On the whole this is much better now, nice one 👍 

I'll open a seperate issue for the `best-answer` side of things, at least so it does not get forgotten.

2021-06-06 20:35 UTC, imorland commented on js/src/forum/components/DiscussionMergeModal.js
> +                    console.log('updating discussion page');
```suggestion
```

2021-06-06 20:35 UTC, imorland commented on js/src/forum/components/DiscussionMergeModal.js
> +                console.log('removing old discussions');
```suggestion
```

2021-06-06 21:11 UTC, imorland approved these changes

2021-06-06 21:11 UTC, merged

2021-06-06 23:53 UTC, datitisev commented
Nooo by debug console.log()s have leaked 😂